### ISSUE TITLE
DXL Power

### ISSUE THREAD

**Issue by dabenpb** [ROBOTIS-GIT/OpenCR-Hardware#2]
I would have suspected that the DXL power would be regulated to 12V but it appears to be whatever is on the SMPS.  Is that what you intend?

**Comment by ROBOTIS-Will** [comment]
Please keep track on the thread below.
https://github.com/ROBOTIS-GIT/OpenCR/issues/251
I'll close this as it is a duplicated issue.
Thank you.

**Comment by dabenpb** [comment]
Thanks.
